### ISSUE TITLE
How to properly specify outmap

### ISSUE THREAD

**Issue by mortonjt** [qiyunzhu/woltka#122]
For instance in [here](https://github.com/qiyunzhu/woltka/blob/master/doc/stratify.md#step-1-taxonomic-classification)

1. Its not clear what `taxonomy/g2tid.txt`, as it doesn't appear to be in the WOL database.
2. Its also not clear what `coords.txt.xz` refers to [here](https://github.com/qiyunzhu/woltka/blob/master/doc/stratify.md#step-2-combined-taxonomicfunctional-classification)

EDIT: To follow up on this, I am trying to run the following command

```bash
    file=<my alignment sam>
    WOL=~/databases/wol
    woltka classify \
        --input $file \
        --map $WOL/taxonomy/lin2tid.txt \
        --nodes $WOL/taxonomy/nodes.dmp \
        --names $WOL/taxonomy/names.dmp \
        --add-rank \
        --outmap ../genome_mappings/$fname \
        -o ../bioms/$fname/species.biom


    woltka classify \
      -i $file \
      --coords $WOL/function/coords.txt.xz \
      --map $WOL/function/uniref.map.xz \
      --map $WOL/function/kegg/ko.map.xz \
      --rank ko \
      --stratify ../genome_mappings/$fname \
      -o ../bioms/$fname/taxfunc.biom
```

And I'm appearing to be running into a few errors, below are what a couple of these errors look like
```
Demultiplexing: on.
Constructing classification system...
  Parsing taxon names file: names.dmp... Done.
  Parsing taxon nodes file: nodes.dmp... Done.
  Parsing simple map file: lin2tid.txt... Done.
Classification system constructed.
  Total number of classification units: 28518.
Classification will operate on these ranks: free.
Read-to-feature maps will be saved to: ../genome_mappings/ERR5532811.
Parsing alignment file ERR5532811_1.sam Traceback (most recent call last):
  File "/mnt/home/jmorton/miniconda3/envs/woltka/bin/woltka", line 8, in <module>
    sys.exit(cli())
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/woltka/cli.py", line 161, in classify_cmd
    workflow(**kwargs)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/woltka/workflow.py", line 122, in workflow
    uniq, major, above, subok, unassigned, stratmap, chunk, cache, zippers)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/woltka/workflow.py", line 274, in classify
    assign_readmap(*rmap, data, rank, sample, **kwargs)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/woltka/workflow.py", line 870, in assign_readmap
    resque = list(resque)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/woltka/classify.py", line 68, in assign_free
    return sub if subok else tree[sub]
KeyError: 'G001643385'
```

EDIT2: so it turns out that the correct taxonomy file is `taxid.map` instead of `g2tid.txt`, now the first command is working.
EDIT3: looks like the coords.txt.xz refers to the protein coordinates [here](https://github.com/qiyunzhu/woltka/blob/master/doc/wol.md#coordinates-based-gene-profiling)

EDIT4: The coords.txt.xz problem has been fixed, but if I run the following script
```
    woltka classify \
      -i $file \
      --coords $WOL/proteins/coords.txt.xz \
      --map $WOL/function/uniref/uniref.map.xz \
      --map $WOL/function/kegg/ko.map.xz \
      --map-as-rank \
      --rank ko \
      --stratify ../genome_mappings/$fname \
      -o ../bioms/$fname/taxfunc.biom
```
I get the following error is given below
```
Demultiplexing: on.
Stratification file directory: ../genome_mappings/ERR5532810.
Constructing classification system...
  Parsing simple map file: uniref.map.xz... Done.
  Parsing simple map file: ko.map.xz... Done.
Classification system constructed.
  Total number of classification units: 47927954.
Reading gene coordinates... Done.
  Total number of host sequences: 10575.
Classification will operate on these ranks: ko.
Parsing alignment file ERR5532810_1.sam Traceback (most recent call last):
  File "/mnt/home/jmorton/miniconda3/envs/woltka/bin/woltka", line 8, in <module>
    sys.exit(cli())
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/woltka/cli.py", line 161, in classify_cmd
    workflow(**kwargs)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/woltka/workflow.py", line 122, in workflow
    uniq, major, above, subok, unassigned, stratmap, chunk, cache, zippers)
  File "/mnt/home/jmorton/miniconda3/envs/woltka/lib/python3.7/site-packages/woltka/workflow.py", line 269, in classify
    stratmap[sample], zippers)
KeyError: ''
```
So it looks like nothing is being outputted by `--outmap` ... @qiyunzhu thoughts on what is going on here?

**Comment by qiyunzhu** [comment]
Hello @mortonjt I think the filpath issue is because this [tutorial](https://github.com/qiyunzhu/woltka/blob/master/doc/stratify.md) is not about the WoL data release, but about the [sample data](https://github.com/qiyunzhu/woltka/tree/master/woltka/tests/data) which is part of the Woltka repo. Let me think about the second question you proposed.

**Comment by qiyunzhu** [comment]
@mortonjt Could you update from the master branch and check again if the issue persist?

**Comment by mortonjt** [comment]
Ah got it.  Thank you for the clarification on the documentation! 

Regarding the install, I'm already on the master branch ...

**Comment by mortonjt** [comment]
Update : it looks like the problem arises if looking at a single sam file - I'm able to get more reasonable results if I pass in the directory.   Not exactly sure what is going on here before - it looks like the sample name is getting dropped somewhere.

Note that enabling woltka on single sam files is highly advantageous since it'll allow for easy parallelism via job arrays as mentioned here : https://github.com/qiyunzhu/woltka/issues/45

On another note, it could be useful for the user interface if the integrity of all of the files was checked before any major computation is executed -- there were several instances where I had a bad output file, but an error wasn't thrown until several hours of computation passed.

**Comment by qiyunzhu** [comment]
I see what went wrong. Woltka can accept a single input file, but in such case the program considers the file as multiplexed, and attempts to extract sample IDs from sequence IDs (e.g., `sample01_read00123`). To disable this behavior and treats a single input file as a single sample, one can add the `--no-demux` flag. This behavior is [documented](https://github.com/qiyunzhu/woltka/blob/master/doc/input.md#demultiplexing), but apparently the documentation isn't in a very obvious place. I think it's better to let the program throw a warning at some point.

**Comment by mortonjt** [comment]
Thanks @qiyunzhu !
