### ISSUE TITLE
Unhandled exception when file has 0 reads

### ISSUE THREAD

**Issue by adswafford** [qiyunzhu/woltka#28]
Somewhat of an edge case, but following host read removal some of our samples, e.g. blanks, can wind up with no reads in the output fastq file. It looks like this causes an unhandled exception with the tool. In the example below, the samples "EXB1C_S201_L002" has zero reads:

grep -A1 EXB1C_S201_L002 /projects/cmi_
proj/blood_microbiome/three_studies/woltka/output_taxonomy.log
Parsing alignment file EXB1C_S201_L002_bowtie2_alignment.sam.xz  Done.
Number of query sequences: 0.

**Error message:**
cat ~/plasma_woltka_strat-1.e1315496
Traceback (most recent call last):
  File "/home/adswafford/miniconda3/envs/woltk/bin/woltka", line 8, in <module>
    sys.exit(cli())
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/woltka/cli.py", line 181, in classify
    workflow(**kwargs)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/woltka/workflow.py", line 115, in workflow
    write_profiles(
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/woltka/workflow.py", line 770, in write_profiles
    write_biom(profile_to_biom(
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/woltka/biom.py", line 54, in profile_to_biom
    row.append(profile[sample][key] if key in profile[sample] else 0)
KeyError: 'EXB1C_S201_L002_bowtie2_alignment'
3224.67user 18.37system 56:16.69elapsed 96%CPU (0avgtext+0avgdata 1623368maxresident)k
10499168inputs+2662904outputs (270major+8321637minor)pagefaults 0swaps

The short term fix is going to be for me to just remove the sam files with no hits and rerun, but likely a small check that n > 0 after parsing the alignment file and then not adding that sample to the dict would do the trick?

**Comment by adswafford** [comment]
Followup:
I moved all the empty files to a new subdirectory called 'empty' and relaunched the script and got a new error:
(base) [adswafford@barnacle.ucsd.edu ~ 10:20 AM]$ cat plasma_woltka_strat-1.e1315514
Traceback (most recent call last):
  File "/home/adswafford/miniconda3/envs/woltk/bin/woltka", line 8, in <module>
    sys.exit(cli())
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/woltka/cli.py", line 181, in classify
    workflow(**kwargs)
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/woltka/workflow.py", line 109, in workflow
    data = classify(
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/woltka/workflow.py", line 219, in classify
    with openzip(fp) as fh:
  File "/home/adswafford/miniconda3/envs/woltk/lib/python3.8/site-packages/woltka/file.py", line 47, in openzip
    return zipfunc(fp, mode)
IsADirectoryError: [Errno 21] Is a directory: '/projects/cmi_proj/blood_microbiome/three_studies/alignment_files/empty'
3199.12user 16.86system 55:17.46elapsed 96%CPU (0avgtext+0avgdata 1620520maxresident)k
189424inputs+2670848outputs (270major+7886183minor)pagefaults 0swaps

So it looks like having a subdirectory in the same folder with the .sam.xz files causes another unhandled exception. I'll move out the subdirectory and launch again.

**Comment by qiyunzhu** [comment]
Hi @adswafford Thank you for reporting this issue! I also just encountered with it after almost finishing crunching the HMP2 dataset. Now have to relaunch... I made a quick patch in PR #29 . I think it will resolve the empty sample issue.

**Comment by qiyunzhu** [comment]
This PR has been merged so this issue is resolved.
